const sampleListings = [
    {
        title: "JW Marriot",
        description: "Best Property in Mumbai",
        image: "https://via.placeholder.com/800x400?text=Landscape",
        price: 15000,
        location: "Juhu, Mumbai",
        country: "India",
    },
    {
        title: "The Ritz-Carlton",
        description: "Luxurious Stay in Delhi",
        image: "https://via.placeholder.com/800x400?text=Landscape",
        price: 20000,
        location: "Connaught Place, Delhi",
        country: "India",
    },
    {
        title: "Hyatt Regency",
        description: "Comfortable Rooms in Bangalore",
        image: "https://via.placeholder.com/800x400?text=Landscape",
        price: 12000,
        location: "MG Road, Bangalore",
        country: "India",
    },
    {
        title: "Grand Hyatt",
        description: "Elegant Hotel in Chennai",
        image: "https://via.placeholder.com/800x400?text=Landscape",
        price: 18000,
        location: "T. Nagar, Chennai",
        country: "India",
    },
    {
        title: "Four Seasons",
        description: "Exclusive Stay in Hyderabad",
        image: "https://via.placeholder.com/800x400?text=Landscape",
        price: 22000,
        location: "Banjara Hills, Hyderabad",
        country: "India",
    },
    {
        title: "InterContinental",
        description: "Premium Experience in Pune",
        image: "https://via.placeholder.com/800x400?text=Landscape",
        price: 16000,
        location: "Koregaon Park, Pune",
        country: "India",
    },
    {
        title: "Sheraton",
        description: "Modern Property in Ahmedabad",
        image: "https://via.placeholder.com/800x400?text=Landscape",
        price: 14000,
        location: "S.G. Highway, Ahmedabad",
        country: "India",
    },
    {
        title: "Radisson Blu",
        description: "Charming Stay in Kolkata",
        image: "https://via.placeholder.com/800x400?text=Landscape",
        price: 15000,
        location: "Salt Lake, Kolkata",
        country: "India",
    },
    {
        title: "Le Meridien",
        description: "Luxurious Hotel in Jaipur",
        image: "https://via.placeholder.com/800x400?text=Landscape",
        price: 17000,
        location: "Raja Park, Jaipur",
        country: "India",
    },
    {
        title: "The Oberoi",
        description: "Top-Rated Stay in Chandigarh",
        image: "https://via.placeholder.com/800x400?text=Landscape",
        price: 19000,
        location: "Sector 17, Chandigarh",
        country: "India",
    },
];

module.exports = { data: sampleListings };
